[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.86.0"
authors = ["Cole Awabdy <contact@coleawabdy.com>"]
repository = "https://github.com/coleawabdy/voxol"
