name: pre-merge
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
jobs:
  check-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
